import { TicketCard, type TicketCardData } from './TicketCard';

/** TicketCard with a server-rendered, signed QR (SVG markup from lib/tickets/qr.ts — generated by the qrcode library, not user input). */
export function QrTicket({
  ticket,
  svg,
  status,
}: {
  ticket: TicketCardData;
  svg: string;
  status: 'valid' | 'used' | 'cancelled';
}) {
  return (
    <div className="relative">
      <TicketCard
        ticket={ticket}
        qr={
          status === 'cancelled' ? (
            <div className="grid size-full place-items-center rounded-[10px] bg-danger-bg text-center text-sm font-semibold text-danger-ink">
              Cancelled
            </div>
          ) : (
            <div
              role="img"
              aria-label="Ticket QR code"
              className="size-full [&>svg]:size-full"
              dangerouslySetInnerHTML={{ __html: svg }}
            />
          )
        }
      />
      {status === 'used' && (
        <span className="absolute top-3 right-3 rounded-full bg-ink px-3 py-1 text-xs font-bold text-white">
          Checked in
        </span>
      )}
    </div>
  );
}
